openapi: 3.0.3
info:
  title: AUTH Token API
  version: 1.0.0
  description: >-
    This describes the API for accessing AUTH Token data including both public
    data on the blockchain, as well as management API for authenticated vendors and apps.

    WARNING: This API is an early draft and in active development. We are changing things
    rapidly. Once we are ready to release a stable version of this API we will notify app developers on Discord.

    ## General

    * all times are in the UTC timezone

    ## Authentication

    Most APIs are read-only and do not require authentication. Any API used for Reward Code management uses User OAuth token, except for the initial authentication endpoints which are secured by OAuth Client key and secret.

    User OAuth tokens are sent via Authorization Bearer header:


    ```http
       Authorization: Bearer [USER_OAUTH_TOKEN]
    ```
paths:
  /codes/redeem:
    post:
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              example:
                redeemed:
                  - code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
                    verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                    wallet: XXXXXX
                  - {}
      summary: Redeem Code
      operationId: Redeem Code
      description: >-
        NOTE: This may not be exposed to users, and instead the only redemption
        path is via theauthtoken.com/redeem portal to allow for tighter Vendor
        integration, including redirecting to a vendor specified URL.

        Permanently redeem a Reward Code and associate it with a reward wallet.
        WARNING: This is irreversable. The response includes a list of
        redeemed codes (typically just one) so that multiple code redemption can
        be added in the future. The actual Reward Code is SAFE to return in this
        case since it has been redeemed already.
 
        + code (string, required) - Reward Code to redeem

        + address (string, required) - Solana wallet address this code will be
        redeemed to

        + email (string) - optional email for entity redeeming code

        + vendorSerial (string) - optional vendor product serial number to
        associate to this Reward Code
      tags:
        - Codes
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
              address: XXXX
              email: me@futurelambo.com
            schema:
              type: object
              properties:
                code:
                  type: string
                address:
                  type: string
                email:
                  type: string
  /codes/{code}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              example:
                codes:
                  - verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                    vendor_slug: ultimatekicks
                    units: 10
                    duration: 52
                    status: redeemed
                    redemption:
                      redeemed_utc: '2022-02-29T04:20:00Z'
                      wallet: XXXXXX
      summary: Code Redemption Status
      operationId: Code Redemption Status
      description: >-
        Check if a Reward Code has been redeemed (either with verification code
        or reward code). Prefer using Verification Codes wherever possible to
        avoid potentially leaking a Reward Code in logs/etc that could be then redeemed by an
        unscrupulous middleman. The actual Reward Code is SAFE to return in this
        case since it has been redeemed already. This is a public API, so no private details
        to the vendor associated with the code are exposed.
      tags:
        - Codes
      parameters:
        - name: code
          in: path
          description: >-
            check using the Verification Code (or the actual Reward Code) if a
            Reward has been redeemed
          required: true
          schema:
            type: string
  /codes/{code}/detail:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content: {}
      summary: Code Details
      operationId: Code Details
      description: >-
        Extended detail on a Reward Code. This is only available when
        authenticated as the Vendor who minted the code originally.
      tags:
        - Codes
      parameters: []
  /codes/{code}/extended:
    post:
      responses: {}
      summary: Update Details
      operationId: Update Details
      description: Update extended detail on a Reward Code. TBD
      tags:
        - Codes
      parameters: []
  /codes/mint:
    post:
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              example:
                label: 2022_ST_PATRICK_PROMO
                vendor_slug: ultimatekicks
                units: 10
                duration: 52
                total_codes: 1000
                codes:
                  - code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
                    verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                  - {}
      summary: Mint Reward Codes
      operationId: Mint Reward Codes
      description: >-
        Mint new Reward Codes for a Vendor (API request must be authenticated as
        the vendor and the Reward Codes will be assigned to that Vendor).

        + label (string, required) - optional vendor supplied label for this
        batch of Reward Codes (private and only visible to the vendor)

        + total (int, required) - the number of Reward Codes that should be minted

        + units (int, required) - the number of Reward Units for each Reward Code

        + duration (int, required) - the number of weeks the Reward Codes will
        be active for once redeemed (1 to 260 weeks)

        NOTE: The cost to the Vendor to mint each Reward Code varies both on the
        Reward Units assigned to each code (per drop) as well as the duration of
        the rewards.
      tags:
        - Codes
      parameters: []
  /codes/batch/{purchaseOrderId}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              example:
                label: 2022_ST_PATRICK_PROMO
                vendor_slug: ultimatekicks
                units: 10
                duration: 52
                total_codes: 1000
                total_redeemed: 312
      summary: Stats Reward Code Batch
      operationId: Stats Reward Code Batch
      description: >-
        Vendor view into the stats for a batch of Reward Codes (number redeemed,
        total, units, duration).
      tags:
        - Codes
      parameters: []
    post:
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              example: {}
      summary: Manage Reward Code Batch
      operationId: Manage Reward Code Batch
      description: >-
        Ability to Manage a batch of Reward Codes by the Vendor. Includes
        assigning various attributes to the batch (after minted). Only the
        original purchasing Vendor of the batch can make modifications.

        + redirectURL (string) - URL that users should be redirected to after
        redeeming a Reward Code (query params will include verification code and
        additional redemption data)

        + label (string) - change the vendor assigned label for this batch of codes
      tags:
        - Codes
      parameters: []
  /vendors:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              example:
                data:
                  - {}
                cursor: E5Mmsd23aP23xYU0
      summary: Vendors
      operationId: Vendors
      description: >-
        List known vendors that support AUTH as registered on the blockchain and
        statistics on their total Reward Codes (issued, redeemed, etc).

        If a cursor field is present in the response, more results are available.
      tags:
        - Vendors
      parameters: []
    post:
      responses: {}
      summary: Register Vendor
      operationId: Register Vendor
      description: >-
        Register a new Vendor, including the intial Vendor onboarding fee or the annual AUTH burn fee. NOTE: This API is not necessary for now as all Vendors go through an approval process and are manually added to the internal database.
      tags:
        - Vendors
      parameters: []
  /vendors/{vendor_slug}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              example:
                vendor_id: 909a550a-3573-4c89-93c7-1b258abc966c
                vendor_slug: ultimatekicks
                brand_name: Ultimate Kicks Shoes
                url: https://ultimatekicksforyou.com
                twitter: ultimatekicksforyou
                reward_catalog_url: https://ultimatekicksforyou.com/rewards
                created_utc: '2021-12-25T15:12:55Z'
                status: active
      summary: Vendors
      operationId: Vendors
      description: ''
      tags:
        - Vendors
      parameters: []
  /oracle/prices/current] [GET:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content: {}
      summary: Historical AUTH Prices [/oracle/prices]
      operationId: Historical AUTH Prices [/oracle/prices]
      description: >-
        Current and Historical Oracle Prices for AUTH

        The current and historical Oracle Prices for AUTH including the block
        that they took effect. Pagination by cursor.
	
        + cursor (optional) (string) Returned from an initial query, allowing client to fetch more results
      tags:
        - Oracle
      parameters: []
  /stats:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              example:
                token_supply: 124112460.312515
      summary: View Stats
      operationId: View Stats
      description: ''
      tags:
        - Stats
      parameters: []
components:
  schemas: {}
tags:
  - name: Codes
  - name: Vendors
  - name: Oracle
    description: Get or publish Oracle prices for the AUTH Token.
  - name: Stats
    description: Blockchain Stats
